[build]
  base = "/"

  publish = "/build"

  command = "yarn build-netlify"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html.br"
  status = 200

[[headers]]
  for = "/*.br"
  [headers.values]
    content-encoding = "br"

