[[Settings]]

ID = "8882f154-976d-4880-899b-4c233f7ce0dc"

[[build]]
  base = "portfolio/"

  publish = "portfolio/build/client"

  command = "yarn build-netlify"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200